### PR TITLE
add HTML tag filter to Crawling pipeline

### PR DESCRIPTION
**Pull request by SebastianSchmidl**

### CODE REVIEW

**Comment by SebastianSchmidl** [comment]
see issue #35

**Comment by SebastianSchmidl** [comment]
we have to remove html before the preprocessor....it should already be removed during crawling!

**Comment by SebastianSchmidl** [comment]
please test with crawler to ensure correctness of the pipelines, as I hadn't enough bandwidth for that

**Review by Benedikt1992 — APPROVED** [review]

**Comment by Benedikt1992** [comment]
please don't remove the branch

**Pull request merged**
